baseURL = "https://oyonder.github.io/art_website/"
languageCode = 'en-us'
title = 'Özlem Yönder Prints'
theme = 'hugo-theme-console'

[markup.goldmark.renderer]
unsafe=true

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  # animateStyle =  "" 

  [[params.navlinks]]
  name = "about/"
  url = "about/"
 
  [[params.navlinks]]
  name = "making/"
  url = "making/"

  [[params.navlinks]]
  name = "collections/"
  url = "collections/" 

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"


  [[params.navlinks]]
  name = "contact/"
  url  = "contact/"

 
